apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TON-ORG/k8s-apps
    targetRevision: main
    path: apps/erpnext
  destination:
    server: https://kubernetes.default.svc
    namespace: erpnext
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
